server:
  port: '7001'

hibernate:
  hbm2ddl:
    auto: create-drop
  cache:
    use_query_cache: false
    use_second_level_cache: false

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  datasource:
    password: kylelovelizzy
    jdbcUrl: jdbc:mysql://13.125.80.45:3306/user-scheme?useUnicode=true&charaterEncoding=utf-8
    username: root
    url: jdbc:h2:mem:yglee
  second-datasource:
    password: kylelovelizzy
    username: root
    jdbcUrl: jdbc:mysql://13.125.80.45:3306/product-scheme?useUnicode=true&charaterEncoding=utf-8
